# Generated by Django 3.2.10 on 2024-07-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_foodmenu_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusimage',
            name='about_us',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
