# Generated by Django 3.2.10 on 2024-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240715_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusimage',
            name='image',
            field=models.ImageField(upload_to='about_us_images'),
        ),
    ]
