# Generated by Django 3.2.10 on 2024-07-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_aboutusimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='details',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(default='image', upload_to='Testimonials'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='proffession',
            field=models.CharField(default='Chef', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(null=True, upload_to='service_icons/'),
        ),
    ]
